### Will allow the inclusion of the correct CPU makefile
CPU_FAMILY = cc26x0

### Include the common makefile
include $(PLATFORM_ROOT_DIR)/wearable3/Makefile.wearable3

CONTIKI_TARGET_DIRS += wearable3/cc2650
