CONTIKI_PROJECT = node

all: $(CONTIKI_PROJECT)

MAKE_MAC = MAKE_MAC_NULLMAC
MAKE_NET = MAKE_NET_NULLNET
PLATFORMS_ONLY = cc26x0-cc13x0

BOARD ?= launchpad/cc2650

BOARDS_ONLY = wearable3/cc2650 launchpad/cc2650 srf06/cc2650 spg-2/cc2650

CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include